on:
    push:
        branches:
            - development

jobs:
    sync-gitea-issues:
        runs-on: docker
        container:
            image: lbausch/laravel-ci:php84
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  ssh-key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
                  ssh-known-hosts: ${{ vars.ENHOSTCODE_KNOWN_HOSTS }}
            - run: composer install
            - run: ./vendor/bin/pint --test
