name: Sync issues with challenges
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
    sync-gitea-issues:
        runs-on: docker
        container:
            image: lbausch/laravel-ci:php82
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - run: composer install
