on:
    push:
        branches:
            - development

jobs:
    sync-readme:
        runs-on: docker
        container:
            image: lbausch/laravel-ci:php84
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  ssh-key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
                  ssh-known-hosts: ${{ vars.ENHOSTCODE_KNOWN_HOSTS }}
            - run: composer install
            - run: php adventofcode sync-readme
            - run: |
                  git config user.name "Zachary Claret-Scott [Bot]"
                  git config user.email "zachary.claretscpott@gmail.com"
                  git add .
                  git commit -m "Updated readme" || exit 0
                  git push
    sync-gitea-issues:
        runs-on: docker
        container:
            image: lbausch/laravel-ci:php84
        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ github.ref }}
                ssh-key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
                ssh-known-hosts: ${{ vars.ENHOSTCODE_KNOWN_HOSTS }}
            - run: composer install
            - run: cp .env.example .env
            - run: sed -i '/^ISSUES_GITEA_HOST=/c\export ISSUES_GITEA_HOST=${{ vars.ENHOSTCODE_ENDPOINT }}' .env
            - run: sed -i '/^ISSUES_GITEA_TOKEN=/c\export ISSUES_GITEA_TOKEN=${{ secrets.ISSUES_GITEA_TOKEN }}' .env
            - run: sed -i '/^ISSUES_GITEA_USER=/c\export ISSUES_GITEA_USER=${{ vars.ISSUES_GITEA_USER }}' .env
            - run: sed -i '/^ISSUES_GITEA_REPO=/c\export ISSUES_GITEA_REPO=${{ vars.ISSUES_GITEA_REPO }}' .env
            - run: php adventofcode sync-gitea-issues
            - run: |
               git config user.name "Zachary Claret-Scott [Bot]"
               git config user.email "zachary.claretscpott@gmail.com"
               git add .
               git commit -m "Updated any gitea issues IDs" || exit 0
               git push
#    sync-github-issues:
#        runs-on: docker
#        container:
#            image: lbausch/laravel-ci:php84
#        steps:
#            - name: Check out repository code
#              uses: actions/checkout@v4
#              with:
#                    ssh-key: ${{ secrets.ACTIONS_PRIVATE_KEY }}
#                    ssh-known-hosts: 'enhostcode.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHg5to4vUFEJ6tqvQ5QX3ptQ8CDgHaxIdJt0XdOMLCiOO4e7781c55sWv19mm/Qy7bIeYQesYuCANZ7LZS1pxyEyhUEOO7SXfgDR/XEWtIrM98OPhCKWFA2dVPaBjWjVnFu3LRy4iH15wCwsyM2diVm72opyCW3eDHDI2C8ijm65TfzGxYzIxkeMeVd3gDFgozNV4mOOrcfvBWCtntlu6hAykMqZp4cMqk468gg6srmcYRd0zvZpJxqHv0sVUQ76zsyFVlVG2XQmq2OGSfjERUgX9GL9ORzsr/9OHWue2PFiSDWPHng7Re0KtbngUwkyUgVge6p34AKrTzT841Lq9lx0RJs0ZGBxJCAx7w3F00hDCxrNMQvvABW5dycaGqyM51XMqFoJbHxDNrfmtYVf21fdDH+joPi88/fPqSMWURplC9gBI45N1ix67L5MwuXFO/xVXul457rKrUck9eLzAkZkeNjwaROks3SmxuDF/IY956gA2L+FyfI75UYrw6jYE='
#            - run: composer install
#            - run: cp .env.example .env
#            - run: sed -i '/^ISSUES_GITHUB_USER=/c\export ISSUES_GITHUB_USER=${{ vars.ISSUES_GITHUB_USER }}' .env
#            - run: sed -i '/^ISSUES_GITHUB_REPO=/c\export ISSUES_GITHUB_REPO=${{ vars.ISSUES_GITHUB_REPO }}' .env
#            - run: php adventofcode sync-github-issues
#            - run: |
#                  git config user.name "Zachary Claret-Scott [Bot]"
#                  git config user.email "zachary.claretscpott@gmail.com"
#                  git add .
#                  git commit -m "Updated any github issues IDs" || exit 0
#                  git push
